/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LeadsRouteImport } from './routes/leads'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as CountdownRouteImport } from './routes/countdown'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComplianceFicaRouteImport } from './routes/compliance/fica'
import { Route as ComplianceFfcRouteImport } from './routes/compliance/ffc'
import { Route as CalculatorsTransferRouteImport } from './routes/calculators/transfer'
import { Route as CalculatorsBondRouteImport } from './routes/calculators/bond'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadsRoute = LeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const CountdownRoute = CountdownRouteImport.update({
  id: '/countdown',
  path: '/countdown',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceFicaRoute = ComplianceFicaRouteImport.update({
  id: '/compliance/fica',
  path: '/compliance/fica',
  getParentRoute: () => rootRouteImport,
} as any)
const ComplianceFfcRoute = ComplianceFfcRouteImport.update({
  id: '/compliance/ffc',
  path: '/compliance/ffc',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsTransferRoute = CalculatorsTransferRouteImport.update({
  id: '/calculators/transfer',
  path: '/calculators/transfer',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorsBondRoute = CalculatorsBondRouteImport.update({
  id: '/calculators/bond',
  path: '/calculators/bond',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/countdown': typeof CountdownRoute
  '/documents': typeof DocumentsRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calculators/bond': typeof CalculatorsBondRoute
  '/calculators/transfer': typeof CalculatorsTransferRoute
  '/compliance/ffc': typeof ComplianceFfcRoute
  '/compliance/fica': typeof ComplianceFicaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/countdown': typeof CountdownRoute
  '/documents': typeof DocumentsRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calculators/bond': typeof CalculatorsBondRoute
  '/calculators/transfer': typeof CalculatorsTransferRoute
  '/compliance/ffc': typeof ComplianceFfcRoute
  '/compliance/fica': typeof ComplianceFicaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/countdown': typeof CountdownRoute
  '/documents': typeof DocumentsRoute
  '/leads': typeof LeadsRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/calculators/bond': typeof CalculatorsBondRoute
  '/calculators/transfer': typeof CalculatorsTransferRoute
  '/compliance/ffc': typeof ComplianceFfcRoute
  '/compliance/fica': typeof ComplianceFicaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/countdown'
    | '/documents'
    | '/leads'
    | '/login'
    | '/pipeline'
    | '/sitemap.xml'
    | '/calculators/bond'
    | '/calculators/transfer'
    | '/compliance/ffc'
    | '/compliance/fica'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/countdown'
    | '/documents'
    | '/leads'
    | '/login'
    | '/pipeline'
    | '/sitemap.xml'
    | '/calculators/bond'
    | '/calculators/transfer'
    | '/compliance/ffc'
    | '/compliance/fica'
  id:
    | '__root__'
    | '/'
    | '/countdown'
    | '/documents'
    | '/leads'
    | '/login'
    | '/pipeline'
    | '/sitemap.xml'
    | '/calculators/bond'
    | '/calculators/transfer'
    | '/compliance/ffc'
    | '/compliance/fica'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CountdownRoute: typeof CountdownRoute
  DocumentsRoute: typeof DocumentsRoute
  LeadsRoute: typeof LeadsRoute
  LoginRoute: typeof LoginRoute
  PipelineRoute: typeof PipelineRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CalculatorsBondRoute: typeof CalculatorsBondRoute
  CalculatorsTransferRoute: typeof CalculatorsTransferRoute
  ComplianceFfcRoute: typeof ComplianceFfcRoute
  ComplianceFicaRoute: typeof ComplianceFicaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leads': {
      id: '/leads'
      path: '/leads'
      fullPath: '/leads'
      preLoaderRoute: typeof LeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/countdown': {
      id: '/countdown'
      path: '/countdown'
      fullPath: '/countdown'
      preLoaderRoute: typeof CountdownRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/fica': {
      id: '/compliance/fica'
      path: '/compliance/fica'
      fullPath: '/compliance/fica'
      preLoaderRoute: typeof ComplianceFicaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compliance/ffc': {
      id: '/compliance/ffc'
      path: '/compliance/ffc'
      fullPath: '/compliance/ffc'
      preLoaderRoute: typeof ComplianceFfcRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/transfer': {
      id: '/calculators/transfer'
      path: '/calculators/transfer'
      fullPath: '/calculators/transfer'
      preLoaderRoute: typeof CalculatorsTransferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculators/bond': {
      id: '/calculators/bond'
      path: '/calculators/bond'
      fullPath: '/calculators/bond'
      preLoaderRoute: typeof CalculatorsBondRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CountdownRoute: CountdownRoute,
  DocumentsRoute: DocumentsRoute,
  LeadsRoute: LeadsRoute,
  LoginRoute: LoginRoute,
  PipelineRoute: PipelineRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CalculatorsBondRoute: CalculatorsBondRoute,
  CalculatorsTransferRoute: CalculatorsTransferRoute,
  ComplianceFfcRoute: ComplianceFfcRoute,
  ComplianceFicaRoute: ComplianceFicaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
